language: go

go:
  - 1.9.x
  - 1.8.x

install:
  - go build -i ./...

script:
  - make GO_FLAGS="-race" test
  - make vet

cache:
  directories:
    - $GOPATH/pkg

notifications:
  email:
    on_success: never
